sudo: required

services:
  - docker

langauge: go

go:
  - 1.16.x

before_install:
  - docker login -u "${DOCKER_GCP_USERNAME}" --password-stdin "${DOCKER_GCP_REGISTRY}" < "${DOCKER_GCP_PASSWORD}"

script:
  - make format-check
  - make build
  - make test
  - make docker

branches:
  only:
    - main
