sudo: required

services:
  - docker

langauge: go

go:
  - 1.16.x

before_install:
  - echo "${DOCKER_GCP_PASSWORD}" | docker login -u "${DOCKER_GCP_USERNAME}" --password-stdin "${DOCKER_GCP_REGISTRY}";

script:
  - make format-check
  - make build
  - make test
  - make docker

branches:
  only:
    - main
